version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=app/app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8000
    volumes:
      - .:/app 
      - ./database.db:/app/database.db 
    restart: always
    command: >
      sh -c "flask db upgrade || (flask db init && flask db migrate -m 'Initial migration' && flask db upgrade) && python -m flask run"
